# Generated by Django 2.0.2 on 2018-07-14 17:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180414_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField((('section_heading', wagtail.core.blocks.StructBlock((('section_header', wagtail.core.blocks.CharBlock(classname='title')),))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock((('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python')])), ('code', wagtail.core.blocks.TextBlock())))), ('html', wagtail.core.blocks.RawHTMLBlock()))),
        ),
    ]
